name = "CalculatedABC"
uuid = "6c2f61f8-fafd-4db0-a534-9240d45f7a9c"
authors = ["Tobias Frilling <tobias@frilling-online.de>"]
version = "0.1.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.2"
Interpolations = "0.12.5"
Plots = "0.27.0"
